### ISSUE TITLE
cannot highlight part of a word

### ISSUE THREAD

**Issue by bksubhuti** [digitalpalireader/digitalpalireader#103]
This is a must.  Cannot highlight part of a word and see the dictionary result.  There is a chance a choice of possible words are given, but not always a correct fit.  It is important because many of the words are compounds and one might want to investigate the individual word meaning even when the whole word is defined.
For example "undershirt" one might want to know what "under" means and "shirt" means separately.  Highlighting a portion of one word is ignored and the whole word is sent for analysis.  android version and I think the old version of DPR had this feature.

**Comment by dangeol** [comment]
I don't understand the problem. One can click on parts of the word in red colour as in the sceenshot.
![image](https://user-images.githubusercontent.com/44405794/75089239-220cc780-5557-11ea-85a0-31af6675b1ee.png)

**Comment by bksubhuti** [comment]
Take for instance pāpanakadhammassāti 

DPR shows nothing.  It can do that.  However Paapa is one word and dhamma is another.
it is actually paapanika (spelled wrong).  So often the old school way is to highlight the sections you think might hit a word (if you know some pali you can do that).  and find the broken up word definitions yourself.  This is a very very common task in the android app written by ven Yuttadhammo.
I think this was often done in the old version as well.  I don't have that anymore. 
screen shot is given.


![Screenshot from 2020-02-22 18-30-49](https://user-images.githubusercontent.com/18184280/75092015-8174d280-556b-11ea-8208-be587174f86c.png)

**Comment by dangeol** [comment]
Same behaviour in the original DPR.

**Comment by parthopdas** [comment]
we can use the following to achieve this
![image](https://user-images.githubusercontent.com/2140460/85480875-1d8b1500-b604-11ea-8339-4c08a2b11ccc.png)

not a priority for now. please reactivate if you feel strongly about this.
