### ISSUE TITLE
strange bug when making research (ask @Martine#8609 for more info on discord)

### ISSUE THREAD

**Issue by MartineMK35** [digitalpalireader/digitalpalireader#109]
![anuloma 1](https://user-images.githubusercontent.com/61345779/75089546-356d6200-555a-11ea-8e5c-8bd60b45a658.PNG)
![anuloma 2](https://user-images.githubusercontent.com/61345779/75089552-38685280-555a-11ea-82a5-73c5ca0842a2.PNG)
![anuloma 3](https://user-images.githubusercontent.com/61345779/75089554-3b634300-555a-11ea-82b3-62af0fbd95a9.PNG)

**Comment by bksubhuti** [comment]
Maybe a language thing.  I get **_anulomaṃ_** running English local with live-server

**Comment by parthopdas** [comment]
discussed with @MartineMK35 sometime back and she mentioned this is not an issue anymore.
