### ISSUE TITLE
Make DPR work offline

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#126]
Acceptance criteria
- [x] PWA with best practices
- [x] Indicator while download is on
- [x] Build process integration
- [x] HTML5/CSS3/ES6 resources downloaded
- [x] XML data files downloaded
- [x] No scenarios requires connection to the internet once downloaded
- [x] Ensure it works with Chrome and Firefox
- [x] Ensure all 3 top level scenarios (nav, search, dict) work full offline
- [x] Ensure all green ticks in all chapters of this tutorial https://codelabs.developers.google.com/codelabs/your-first-pwapp

**Comment by dangeol** [comment]
https://github.com/dangeol/digitalpalireader/tree/make-dpr-work-offline
