### ISSUE TITLE
Support Bangla

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#132]
AC
- [x] Bengali should be rendered just like roman/Thai/Devanagari etc.
- [x] Adding a new menu item to _dprhtml\features\settings-dialog\main-pane.html
- [ ] Adding new menu items to _dprhtml\features\bottom-pane\main-pane.html
- [ ] Bengali dictionary integration corresponding to PED, CPED and DPPN.
- [ ] Bengali translations integration

**Comment by yuttadhammo** [comment]
b854d7b25c2f751222992713f5036ca24d29a141

**Comment by parthopdas** [comment]
closing for now. to be reactivate when there is requirement.
