### ISSUE TITLE
Complete static analysis of all the texts without doing anything in the FE.

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#133]
From Vasil on discord:

![image](https://user-images.githubusercontent.com/2140460/75836316-4bf2a380-5e0d-11ea-9440-a4fe41487d13.png)

**Comment by olastor** [comment]
Hi, I'm not sure if it is related to this issue in detail, but I found this published paper which deals with morphological analysis of pali:

- https://arxiv.org/pdf/1510.01570.pdf
- https://github.com/daalft/PaliNLP

There is some Java Code available in the repo, which could be reimplemented in JavaScript maybe if it's useful.

I don't know how search is handled in the DPR, but usually you would apply language specific stemming to the search query and the texts in the database in search engines.

**Comment by olastor** [comment]
maybe this discussion is also related: https://discourse.suttacentral.net/t/pali-compounds-breaking-them-a-better-way/7253

**Comment by parthopdas** [comment]
this is not a priority in the near future so closing to clean up the backlog. we can reactivate if we think we are going to fix it.
