### ISSUE TITLE
opened a specific sutta which stars with 'evaṃ me sutaṃ...', clicking 'evaṃ' I see the word defined in the dictionary as 'Evaŋ'

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#137]

**Comment by bksubhuti** [comment]
this is the old notation.  I suggest a global search and replace on the dictionaries.

**Comment by parthopdas** [comment]
@sumbodhi can you also please look into this.

**Comment by sumbodhi** [comment]
I suggest this is delayed until #131 is resolved. If there is pre-processing it can be handled there.

**Comment by parthopdas** [comment]
discussed this with @yuttadhammo sir - he is fine with either. 

so please feel free to raise a PR with the changes.
