### ISSUE TITLE
Search needs exact word option and  "starts with"

### ISSUE THREAD

**Issue by bksubhuti** [digitalpalireader/digitalpalireader#143]
Search needs exact option and also a  "Starts with" option.
small words are too cumbersome to find and bog down the search results when it is not neccessary.  Many times the "fuzzy" is good.  But not always.

**Comment by yuttadhammo** [comment]
Use regular expressions for this. \b = word boundary.

https://www.digitalpalireader.online/_dprhtml/index.html?feature=search&type=0&query=\basu\b&MAT=mat&set=dmsak&book=1&part=1&rx=true
