### ISSUE TITLE
Dictionary search results cannot be navigated to

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#150]
Steps to repro:
1. Goto http://localhost:8080/DPRHTML/index.html?feature=dictionary&type=ATT&query=arahant&opts=xv,xd,xm,xs,xa,xk,xy,mm,ma,mt,hd
1. Click on dātumarahantī 
1. Click on the white rectangle which should navigate to http://localhost:8080/DPRHTML/index.html?loc=k.12.3.4.0.12.0.a&query=d%C4%81tumarahant%C4%AB&para=63

Obtained:
- Noting comes up, the spinner keeps spinning

Expected:
- Relevant content

Notes:
- It appears that location itself does not exist
- There are errors in chrome console.

Parity with DPR-Palemoon
- Same issue exists in DPR-Palemoon

**Comment by DPRAdmin** [comment]
[partho] verified on staging.
