### ISSUE TITLE
Multi-word highlighting does not happen

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#151]
**Steps to repro:**
- Goto http://localhost:8080/DPRHTML/index.html?loc=k.1.0.0.13.0.0.m&query=khant%C4%AB%20parama%E1%B9%83%20tapo%20titikkh%C4%81&para=17

**Obtained:**
- Taken to the relevant location but without the matching phrase highlighted

**Expected:**
- Matching phrase to be highlighted. See below for pic.

**Notes:**
- Single word highlighting work as expected.

**Parity with DPR-Palemoon**
- It works as expected in palemoon
   ![image](https://user-images.githubusercontent.com/2140460/76379939-3517f800-639d-11ea-95de-13b4c1b4db35.png)

**Comment by dpruser** [comment]
[parthopdas] Closing after verification.
