### ISSUE TITLE
Enable Pali Learning Utilities 

### ISSUE THREAD

**Issue by smkvr98** [digitalpalireader/digitalpalireader#158]
- [ ] Introduce a Tab in the sidebar  which includes a list of links to resources ( that are implemented ) dealing with Pali Learning Utilities   .
- [ ] Handle feature parameter value "PaliLearn" in the url  . ( ?feature=PaliLearn )

Take 2:
- [ ] New tab for Pali Learning utils.
- [ ] New url feature pali

**Comment by parthopdas** [comment]
de-prioritized based on a conversation with @yuttadhammo & @shraddha314
