### ISSUE TITLE
Implement Quiz 

### ISSUE THREAD

**Issue by smkvr98** [digitalpalireader/digitalpalireader#159]
Implement Quiz as a part of Pali Learning Utilities . 

  ### Implement Vocabulary Quiz 
 - [ ] Pali-English 
 - [ ] English-Pali
 
### Implement Nouns Quiz 
  - [ ] Paradigms 
  - [ ] Individual 
  - [ ] Shuffle 
  

 ### Implement Verbs Quiz
  - [ ] Paradigms
  - [ ] Individual
  - [ ] Shuffle
  - [ ] English

**Comment by parthopdas** [comment]
de-prioritized based on a conversation with @yuttadhammo & @shraddha314
