### ISSUE TITLE
Add Pali Learning Resources

### ISSUE THREAD

**Issue by smkvr98** [digitalpalireader/digitalpalireader#160]
Include Pali learning resources in DPR-Web .

### Grammar Docs
- [x] Include _A Practical Grammar of the Pāli Language_ by _Charles Duroiselle_ .
- [x] Include _Pali Translation Cheat Sheet_ by _Alan McClure_ . 
- [x] Include _Elementary Pali Compound Reference Sheet_ By _Alan McClure_ .

### Abbreviation Lists
- [x] Include PED Abbreviations
- [x] Include CPED Abbreviations

**Comment by parthopdas** [comment]
de-prioritized based on a conversation with @yuttadhammo & @shraddha314

**Comment by yuttadhammo** [comment]
The Duroiselle grammar is already in the project, if you could just add a link to it, that would be great.

**Comment by yuttadhammo** [comment]
It's online here: https://www.digitalpalireader.online/digitalpalireader/content/etc/grammar/GMD/

**Comment by smkvr98** [comment]
Will work on formatting for the rest of the files but the "Pali Grammar by Charles Duroiselle" doc should be up and useable . Any other resources you'd want to include in the list Bhante @yuttadhammo ?

**Comment by yuttadhammo** [comment]
Not personally, thank you.

**Comment by parthopdas** [comment]
This is how it looks now. It is a stop gap arrangement for sure, so we can move as necessary.

![image](https://user-images.githubusercontent.com/2140460/80912677-f8a3bf80-8d81-11ea-9c0d-d4adc6675306.png)
