### ISSUE TITLE
[ven. bodhirasa] Some updates to the patterns that DPR Analysis is not catching properly 

### ISSUE THREAD

**Issue by DPRAdmin** [digitalpalireader/digitalpalireader#180]
AC
- [ ] https://docs.google.com/document/d/14jRfEit8lSNwgVjgnWuMOj1wpMqj9WYO11s4F9jFDrs/edit?usp=sharing

**Comment by parthopdas** [comment]
closing as per discussion in team meeting. any remaining issues will be fixed down the line.
