### ISSUE TITLE
Suttas are not opening properly from hierarchy

### ISSUE THREAD

**Issue by DPRAdmin** [digitalpalireader/digitalpalireader#181]
AC
- [ ] Suttas are not opening properly from hierarchy. Tested with Khuddaka > Sn (Sutta Nipāta) > 3. Mahavagga > 12. Munisuttaṃ, and doe not open by clicking "View this section" button. But quick link kn5.12 worked fine. Also tested with Byākaraṇa > Kac > mahākaccāyanasaddāpāṭha > 6. ākhyāta and does not open.
- [ ] Some books have a third level of hierarchy which is not displaying (intermittently - now it does). For example in Byākaraṇa select Kac(cāyana), in the hierarchy select mahākaccāyanasaddāpāṭha > ākhyātakappa. There should be 4 khandas, paṭhamakanda, dutiyakanda, etc. Cross check with Palemoon, there is a 3rd level of hierarchy missing. just checked again, not it is not working, so an intermittent fault.
- [ ] couple of cases from martine
- [ ] couple of cases from shraddha

**Comment by bdhrs** [comment]
Here's an example
1. In Set, click on Majjhima Nikāya. 
2. In Set, click on Vism. 
3. Hierarchy is displaying 1st layer (paṭhamo bhāgo) & 2nd layer (1. sīlaniddeso), but the third layer (sīlasarūpādikathā) is missing. 
4. The third layer of hierarchy appears if you click on 2. dhutaṅganiddeso and then click back on 1. sīlaniddeso
![hierarchy](https://user-images.githubusercontent.com/64521731/80581278-9027ac00-8a2a-11ea-807f-f8b7b1b7e09e.gif)

**Comment by parthopdas** [comment]
These should now be fixed after completely moving nav sidebar to ko.
