### ISSUE TITLE
Issues with searching for sanskrit roots

### ISSUE THREAD

**Issue by DPRAdmin** [digitalpalireader/digitalpalireader#182]
- [ ] When searching in Sanskrit roots, the search results do not display if you have done a previous search in PED with the advanced option "full text" turned on. This glitch also exists in Palemoon. To duplicate this, go to sidebar > dictionary, select PED > advanced options > full text. search for anything, "vatt". then keep "full text" on, go to Sanskrit roots and search for bhuu. no results. Turn "full text" option off in PED and it works again.

**Comment by yuttadhammo** [comment]
Fixed in 1a391bbc356c7e1f307f634f624711e187e72dcc but all options should switch off after changing to Skt root search, as they are listed as unavailable.

**Comment by bdhrs** [comment]
still doing the same thing. it looks like this.
![PED full text search](https://user-images.githubusercontent.com/64521731/81060824-e1cfab00-8ef0-11ea-8da7-d46a93c3ab08.gif)

**Comment by yuttadhammo** [comment]
You're using the production version. Changes are only seen in the staging version until release. Try https://staging.digitalpalireader.online/

**Comment by bdhrs** [comment]
right you are!
