### ISSUE TITLE
error in importXML send_sidebar.js - can't display book section

### ISSUE THREAD

**Issue by dangeol** [digitalpalireader/digitalpalireader#188]
Bug observed on staging today, 2020-04-26:
When clicking several times through different book sections in navigation using the right arrow button, then using quick link, and then again using the arrow button for a section, the error as in the screenshot might appear. The error is a bit hard to reproduce.
![image](https://user-images.githubusercontent.com/44405794/80315377-823e1500-87f7-11ea-804a-ac64c4eb77b2.png)

**Comment by parthopdas** [comment]
this should be fixed now after completely moving navigation pane to ko.
