### ISSUE TITLE
ven bodhirasa: Problem with the numbering in Saṃyutta Nikāya

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#190]
[[More info](https://docs.google.com/document/d/1deroZtIW9y8gn2-l4_FZRD4juwMfqCCVtYwtY2ErZD8/edit)]

- There is another problem with the numbering in Saṃyutta Nikāya. For example if i use the Quick LInk to open SN 35.93. That should be dutiyadvayasuttaṃ but instead SN 35.110 upādāniyasuttaṃ opens. Look at the title bar, DPR thinks it's SN 35.93, but look at the paragraph number, it is in fact 35.110.

![image](https://user-images.githubusercontent.com/2140460/80431896-0dbdc000-8936-11ea-8188-95ed8de7c726.png)

If I manually open SN 35.93 using the hierarchy, I can see that DPR thinks it is SN 35.76, but the paragraph number 93 is correct and so is the sutta name. (Great sutta by the way!)
Very simply, DPR should match the paragraph numbers, as they are the sutta numbers. 

Update: I’ve found the point where it goes wrong. SN 35.1-32 are all correct. Then...

Actual Sutta/Paragraph	DPR thinks it is
33				33
34-42				33
43-51				34
52				35
53				36	
54				37
Then it stays consistently out from then until
171-173			154
174-176			155
177-179			156
180-182			157
183-185			158
186				159
Then the next problems starts again at
189-191			162
192-194			163
195-197			164
198-200			165
201-203			166
204				167
Then every time there are two suttas in one, it goes out further. You should be able to see the pattern.

**Comment by yuttadhammo** [comment]
fixed in 3ff9cbac1eed0257137602e42eca48b208925ccc

**Comment by parthopdas** [comment]
@shraddha314 pointed out a few more glitches that she will discuss with you tomorrow. its possible that they are not glitches, i which case, please resolve it back.

**Comment by yuttadhammo** [comment]
should all be fixed as of 4032a9d0e20e8ae7645c91e8b03141431320a7e4
