### ISSUE TITLE
ven bodhirasa: Saṃyutta Nikāya translation only opens on the index

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#196]
A request from my students - last week I gave them lots of exercises from the Saṃyutta Nikāya. When they open the translation, it does not open on the sutta like all the other Nikāyas do, but only opens on the index. Then one has to manually find one’s way to the sutta. Is it possible to bring the behaviour of the Saṃyutta Nikāyas translations in line with all the others? Still, it is quicker than looking up the translation in a book. 

![image](https://user-images.githubusercontent.com/2140460/80547615-09f47100-89fc-11ea-9528-9288767bd6ef.png)

**Comment by yuttadhammo** [comment]
fixed in eb15383196eab9771e2e4faca4022c09b5bf7b65
