### ISSUE TITLE
Title Bar weirdness

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#198]
There is something strange about the title bar. All the names bunch up on themselves like curtains instead of flowing naturally. Perhaps it would be more visually appealing if the whole row of text just naturally rolled onto a second line when necessary, instead of each section scrunching up onto its own second line. This one below does not even fit completely on the page, the text is chopped off at the end.
![title bar 3](https://user-images.githubusercontent.com/64521731/80580802-c4e73380-8a29-11ea-8af5-3b353bf8c162.png)

**Comment by Devamitta** [comment]
I agree. Specialty if you have a small screen.
For small screens maybe it would be nice to make this title bar disappeared when you scroll down, and appears again when you scroll up. Like in SuttaCentral for example.

**Comment by parthopdas** [comment]
vens @Devamitta @bdhrs  Fixed now on staging - please reactivate if any issues persist.
