### ISSUE TITLE
Velthuis does not work in Pāli Root Search

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#213]
In Pāli Root Search, only Unicode diacritics work, see the pic below. In both cases the search is for maa / mā (to measure), but only the second search gives results

![pali root search](https://user-images.githubusercontent.com/64521731/81495083-54fb6780-92cb-11ea-85ea-951d7086777a.gif)

**Comment by yuttadhammo** [comment]
fixed in fb74fe08e17b418f0f4a06bc2710d5e998b4faf4
but it is mostly irrelevant because velthius is converted to uni in the search box on the fly now
