### ISSUE TITLE
Search with regular expressions not working properly "+"

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#215]
The **+** sign is a great feature in search, finding two words in the same paragraph. But when Regex is turned on, **+** should function in its normal Regex capacity, not as "look for another word".

One of the most powerful and useful Regex search functions is **.+** which is an indefinite wildcard, which finds any text. For example **atha kho.+etadavoca** should find any text beginning with **atha kho** followed by any number of characters and ending with **etadavoca**. This doesn't work because the "+" is hardwired to find another word.

This behaviour is consistent with Palemoon.

**Comment by yuttadhammo** [comment]
.+ isn't really an accepted wildcard I don't think. You should use .* instead, I think.

**Comment by bdhrs** [comment]
"." is the wildcard, "+" gives it superpowers. It is used in combination.
I'll make a vid to demonstrate how useful it is.

**Comment by yuttadhammo** [comment]
I think the expression you should be using is **.***, not **.+**

**Comment by yuttadhammo** [comment]
The difference is that .* matches 0 or more, .+ matches 1 or more. .* is more commonly recognized I think.

**Comment by yuttadhammo** [comment]
..* would be equivalent to .+ afaics.

**Comment by bdhrs** [comment]
having run a few tests, * works in most of the cases, the only unfortunate side effect is it "eats" the letter before it - i think that's what you mean by 0 or more matches, as opposed to 1 or more matches. if there is some difficulty in integrating the +, * can be used, no problem.

**Comment by yuttadhammo** [comment]
If you want the same results as .+ I think ..* should act the same.

**Comment by parthopdas** [comment]
ven @bdhrs please reactivate if the resolution if issues still remain or the workaround does not work. 

.+ is the same as ..* so if issues remain please also give an example.
