### ISSUE TITLE
SET & BOOK's titles in elaborated form than short

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#218]
From Arpan Chakma
> I think, it'll be well to keep the SET & BOOK's titles in elaborated form than short, specially for Bangla script it’s a very important. e.g. roman Vism, in Bangla short form  it denotes another meaning

**Comment by yuttadhammo** [comment]
I've altered the abbreviations to make them more legible in foreign scripts, using periods and dashes to separate parts. I'm not sure we want to give up using abbreviations.
80c595aea842fa80a9135c89485d87151c79cce7
