### ISSUE TITLE
A minor glitch in SN35

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#223]
The Bhikkhu Bodhi translation of SN 35.240 is numbered SN35.**2240**, which causes the translation opens on the index instead of the sutta itself. 

![SN35 2240](https://user-images.githubusercontent.com/64521731/82174229-9902f380-98ed-11ea-9dd5-aad024edba6c.png)

It's a great practical sutta for those that don't know it : )

**Comment by yuttadhammo** [comment]
I don't understand what I can do to solve this... are you just saying it is a typo? In that case, just remove the first 2.

**Comment by bdhrs** [comment]
yes, bhante, it is just a typo in the buddhist texts archive. if i was a programmer and knew how to do it, i would certainly just remove the first 2 ; ) 
![2240](https://user-images.githubusercontent.com/64521731/85970782-1475bb80-b9e9-11ea-86b5-1a78208026e0.png)

**Comment by parthopdas** [comment]
Sorry I assumed this was an issue with the sutta mapping data model - hence assigned it to Sir.

I'll fix this and let you know.

**Comment by parthopdas** [comment]
Fixed as discussed
