### ISSUE TITLE
Different html formatting in main screen and search screen

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#225]
There seems to be different html formatting in the main screen vs the search screen. Search screen seems to use the preferences font and size and background, while the main screen doesn't.

![screen main](https://user-images.githubusercontent.com/64521731/82198258-aafa8b80-9919-11ea-94e2-e8fea48a98a0.png)
![screen search](https://user-images.githubusercontent.com/64521731/82198465-fca31600-9919-11ea-9b27-46f586ead4e2.png)

**Comment by parthopdas** [comment]
v. @bdhrs please reactivate if not fixed. you can test out the fix on http://staging.digitalpalireader.online/
