### ISSUE TITLE
Single book search isn't working in new windows

### ISSUE THREAD

**Issue by yuttadhammo** [digitalpalireader/digitalpalireader#231]
When performing a search using the single book option, the DPR crashes trying to load the xml file, as the book # is null, because the book <select> is empty. Somehow it isn't getting initialized like it would with a full search.

https://www.digitalpalireader.online/_dprhtml/index.html?feature=search&type=2&query=Loko&MAT=mat&set=m&book=1&part=1&rx=false

This link doesn't work, but it would if one had performed a full search first to initialize the <select>

**Comment by parthopdas** [comment]
fixed by #234
