### ISSUE TITLE
Change "M.N. X.Y" to "MN X.Y" in the header.

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#235]
[User: ven. Devamitta]
Before, in offline version when I open any sutta it show the number (MN 10.2) and I can easily search just past this number in DPR. But now it have another system M.N. 10.3 and I can not just past it in navigation in DPR. I have to remove dots.

**Comment by yuttadhammo** [comment]
This was by design, because we aren't always using Roman script. Shortlinks should work with . now.

**Comment by yuttadhammo** [comment]
Oh, wait.

**Comment by yuttadhammo** [comment]
Fixed
