### ISSUE TITLE
Next Sutta button in ABTs breaks the page

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#237]
The Next Sutta button in translations from Ven. Ānanadajoti's Ancient Buddhist Texts site causes the DPR page to break. DPR disappears entirely, leaving only the translation. 
![ancient buddhist texts](https://user-images.githubusercontent.com/64521731/83627090-0da78480-a5b4-11ea-83c8-0d276a530be3.gif)

**Comment by parthopdas** [comment]
Fixed by ven. anadajoti.
