### ISSUE TITLE
[shraddha] Issues + feedback on history tab

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#238]
1. It shows a list of previously visited page but when clicking on a page, it just shows the page as shown below. I would have expected it to take me to that specific page for the sutta I selected from History.
  ![image](https://user-images.githubusercontent.com/2140460/83632737-224f4100-a5e3-11ea-925f-9224bafe7f12.png)
2. Once I click a page from the right hand side, the page opens but the selected sutta  on booxmark field stays even if it doesn't match what is open. Also because it doesn't reset, the label as History for that box doesn't come back. So, now it just looks like part of book heirarchy. Maybe Add a new box similar to the box for quicklinks or Navigate Book Heirarchy with title called "History" (and maybe later can be "History & Bookmarks")
  ![image](https://user-images.githubusercontent.com/2140460/83632793-3b57f200-a5e3-11ea-91b7-ef2e9136ba74.png)
3. Ctrl+click works - opens in new tab for the Buttons on Heirarchy and Quicklink button.  Ctrl+click on History also opens the same thing selected on heirarchy in new tab. Is that intentional?

**Comment by dangeol** [comment]
As discussed, we can leave it as it is for now.
