### ISSUE TITLE
Ability to look up definitions & perform analysis from the search results page

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#260]
![image](https://user-images.githubusercontent.com/2140460/85990493-76f4a900-ba35-11ea-92e2-47af87dd401b.png)

**Comment by bdhrs** [comment]
please include search results generated from tools > search "aṭṭhakathā terms" and "ṭīkā terms"

**Comment by parthopdas** [comment]
deployed to prod
