### ISSUE TITLE
Mobile usability fixes - 1

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#266]
- [x] swipe right to left for next sutta, swipe left to right for previous sutta. android tipitaka has that functionality and it's very useful.
- [ ] https://dhammatalks.org mobile site type bottom bar 
  ![image](https://user-images.githubusercontent.com/2140460/103611132-5b7ed380-4f6d-11eb-9225-3fc264b6d519.png)
- [ ] move footer to the sidebar
- [ ] close context menu automatically on mobile
- [ ] set and book should be single line high
- [ ] click on the "go to" button from nav/search/dict bars should collapse the side bar automatically

**Comment by dangeol** [comment]
It would also be nice to improve the layout of the "Install components for offline use" screen by adding a margin between each download item.
![image](https://user-images.githubusercontent.com/44405794/103091498-a35c3d00-45f4-11eb-98b7-fb5317e63d5f.png)

**Comment by bdhrs** [comment]
some ideas for mobile usability

swipe right - next sutta (same as pressing this button or n shortcut)
![next](https://user-images.githubusercontent.com/64521731/103163608-ea7d4480-4825-11eb-9753-c8f2a05e6b38.png)

swipe left - previous sutta (same as pressing this button or p shortcut)
![back](https://user-images.githubusercontent.com/64521731/103163612-01239b80-4826-11eb-99ff-b1ea0243517d.png)

swipe from left edge towards centre - open sidebar drawer (same as pressing this button or ` shortcut)
![sidebar](https://user-images.githubusercontent.com/64521731/103163616-1a2c4c80-4826-11eb-93d7-3faa07895b57.png)

swipe from top edge downwards - open menu (same as pressing this button)
![open menu](https://user-images.githubusercontent.com/64521731/103163618-27493b80-4826-11eb-9f58-38252e9b86b3.png)

**Comment by catalin-i** [comment]
Update on this - The swipe actions have been implemented for quite a while. Didn't address the other points since this was the one that was causing the most friction.

Right now, the other ones do not have high priority. Let me know if there is still something here that is causing considerable friction.

**Comment by parthopdas** [comment]
fine for now.
