### ISSUE TITLE
Search result: Subcommentary link not working

### ISSUE THREAD

**Issue by dangeol** [digitalpalireader/digitalpalireader#276]
From the feedback form (April 2020, still an issue):
Impossible to see the vinaya subcommentary when I clicking on the corresponding arrow in the search result.

Direct link:
[https://www.digitalpalireader.online/_dprhtml/index.html?feature=search&type=0&query=pa%E1%B9%ADibh%C4%81ti&MAT=mat&set=vdmsakyxbgn&book=1&part=1&rx=false](https://www.digitalpalireader.online/_dprhtml/index.html?feature=search&type=0&query=pa%E1%B9%ADibh%C4%81ti&MAT=mat&set=vdmsakyxbgn&book=1&part=1&rx=false)

<img width="1147" alt="Screen Shot 2020-04-24 at 9 52 15 AM - Eazy Am" src="https://user-images.githubusercontent.com/44405794/94991739-4321a600-0585-11eb-815a-5a72a2580916.png">
<img width="1151" alt="Screen Shot 2020-04-24 at 9 51 11 AM - Eazy Am" src="https://user-images.githubusercontent.com/44405794/94991741-474dc380-0585-11eb-80c3-e23f92752e3e.png">

**Comment by bdhrs** [comment]
i have the same issue, especially with vinaya texts, it seems to work when the mūla of that text is open, but cannot go "cold" to the tika.
