### ISSUE TITLE
In which translit files should I make update?

### ISSUE THREAD

**Issue by puerdon** [digitalpalireader/digitalpalireader#278]
I just found a bug in the "x-to-Thai" converter. I would like to fix the bug and make contribution.

But after forking and cloning it to my computer, I found three files with similar codes of the function:

- `xul/digitalpalireader/content/js/translit_overlay.js`
- `xul/ThunDPR/content/js/translit_overlay.js`
- `_dprhtml/js/translit.js`

I wonder what are these different files with similar functions for? Do I need to make update to these three files?

**Comment by parthopdas** [comment]
hi @puerdon apologies for the delay in responding. And thank you for offering to help out.

For now I have copied over the transliteration code from another project. So please check if the issue you are referring to is fixed.
If not, please go ahead a send a PR for the fix. The files you want to focus on are translit.js and translitCore.js.
