### ISSUE TITLE
Mobile phone screen sleep mode interferes with offline installation

### ISSUE THREAD

**Issue by dangeol** [digitalpalireader/digitalpalireader#281]
Feedback from Bhikkhu Subhuti:

Download hanging at 2%.
> [...] it does not do the install stuff when the screen is turned off .  (on a phone that is 30 seconds or less).  so i have to baby sit and keep my phone awake to install this app.. it might be a browser limitation but should be looked into and maybe some instructions to turn off screen sleeping.
![image](https://user-images.githubusercontent.com/44405794/96584108-0c19f700-12de-11eb-8396-a4368ce2e446.png)

**Comment by parthopdas** [comment]
browser limitation, we'll let the user deal with it the way they want.
