### ISSUE TITLE
BuddhistTexts not working

### ISSUE THREAD

**Issue by unseeingdog** [digitalpalireader/digitalpalireader#282]
In the downloads tab is an option to download BuddhistTexts for offline use, which returns an error every time I click it.

Also in the options there is "use BuddhistTexts archive", but when I tried enabling and using the example link for the BuddhistTexts Android app it doesn't seem to do anything.

It would be good to be able to integrate this as it does have translations for the full 4 Nikayas, which dhammatalks.org and ATI do not.

**Comment by parthopdas** [comment]
BT is now available right out of the box. No configurations needed. Please check and let me know if it isnt working for you.

**Comment by unseeingdog** [comment]
Ah I see, I just checked and it seems to be available online. However downloading for offline use still gives me an error.

**Comment by parthopdas** [comment]
@unseeingdog hmm there was a default setting change recently that made BT available out of the box.

can you please press the hard reset on the settings dialog and try downloading again? we should not need to do this again and again.
![image](https://user-images.githubusercontent.com/2140460/101698071-a586ad80-3ac4-11eb-8f00-00f1fdaa5a87.png)

**Comment by unseeingdog** [comment]
I hadn't tried that before, but it seems it didn't help. It still shows the same error for downloading, on different browsers as well. When I switch off the internet connection and try to open BT this happens:
![Screenshot_20201210-045341_Bromite](https://user-images.githubusercontent.com/53958588/101700857-cab6f400-3aa3-11eb-86c1-dc3f38371dd9.jpg)

**Comment by parthopdas** [comment]
In about 15 mins time from the timestamp of this message - can you please trying again but this time on staging
Here are the steps
1. Open https://staging.digitalpalireader.online/_dprhtml/index.html
1. Ensure build number on the footer is "5.20.1209.06"
1. Try downloading BT (and if you can DT and ATI as well - I just made some changes so your testing will help greatly!)

Let me know how it goes.

**Comment by unseeingdog** [comment]
OK, so here BT does start the download but only gets to exactly 50%, then shows the same error as before. 

ATI does not even start and fails right away, and loading ATI online now strangely just shows the DPR home page. On the normal site ATI works perfectly. 

Downloading and viewing DT works fine here too.

**Comment by parthopdas** [comment]
Very appreciative of your patience & help in sorting this out.

I pushed in another fix and also tested by downloading all the components on chrome private mode on andriod.

Could you please try the following on staging: 
- Reset the settings (the red button above)
- Ensure you are seeing 5.20.1210.01 in the footer
- Download the components 
- If any of the components fail midway, please retry the download once more and letting me know.

NOTE: Regarding the last step we do retry 5 times but sometimes we have see the intermittent outages not covered by that.

**Comment by parthopdas** [comment]
Type above - my apologies - please ensure the build version you see is 5.20.1210.03

**Comment by unseeingdog** [comment]
Ok, tested version 5.20.1210.08. ATI and DT did work this time but BT stopped at 50% again. I tried a few times hours apart but no luck.

**Comment by parthopdas** [comment]
@dangeol are you able to look into it. I am actually at a loss what's going on here. 
I did push in a couple of fixes already & Max & I tested it out. So it will require some playing around.

Note that it is different from the the one from v bdhrs' retreat. 

if you are up for it please let me know so i can provide you with the initial briefing.

**Comment by dangeol** [comment]
I've run several trials with the latest versions of Firefox and Chrome Browsers on Android and Windows 10.

With Chrome on Windows 10, and with the two ad blockers _Ghostery_ and _uMatrix_ being activated, the installation error happened twice out of six trial runs, at between about 50 and 70%. Each time, a random *.htm file request was blocked. It did not happen with deactivated ad blockers (number of runs: five). It's a hint but no proof that the ad blockers actually are the culprit.

![InstallError](https://user-images.githubusercontent.com/44405794/103101401-baf8ed00-4617-11eb-9c38-1cde68c2811e.PNG)

**Comment by parthopdas** [comment]
@dangeol you're a genius. This is hard core debugging. I have no idea how you zeroed in on adblockers of all things. Really nice work! ❤️

**Comment by parthopdas** [comment]
@unseeingdog we have just deployed to production, please reactivate if this is still an issue.
