### ISSUE TITLE
Text jumps when opening and closing a new window side-by-side

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#283]
I remember a time when this was working properly, but now it seems to be wonky again. When opening or closing a new window side-by-side with the current window, the text in the sutta and translation jumps up and down. Here's an example below. 

- I have highlighted the corresponding text in a sutta and translation, then open the commentary side-by-side
- the text jumps places when the new window opens side-by-side
- and the highlight gets lost in the sutta (but not in the translation)
- When closing the side-by-side window, the sutta text remains stationary
- but the translations jumps.  
- When closing, highlights in the sutta and commentary remain. 

It can be really challenging to find the right place again with long suttas, and even more so with translations which encompass hundreds of suttas.
![jumping text](https://user-images.githubusercontent.com/64521731/98793600-2010ce80-242e-11eb-8a77-2d22aea8556d.gif)

**Comment by parthopdas** [comment]
Fixed by changes to #286
