### ISSUE TITLE
Pali Language Resources not working offline

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#285]
**Acceptance Criteria**
- [ ] Refresh to get latest build, go offline, ensure pāli resources are accessible.

Note: Not required to download any component as the above will be install as part of the base shell component.

======

Perhaps these can be added to the list of offline downloads. Duroiselle's Grammar is particularly useful. 

![pali resources doh!](https://user-images.githubusercontent.com/64521731/98795278-096b7700-2430-11eb-961f-0af2c0cbc0a9.gif)

**Comment by MaxxJohnson** [comment]
In Duroiselle's grammar, these links in the contents don't work, and most of these sections seem to be missing from the text as well:

Visama class (635)
Vatta (636)
Kinds of vatta (638)
Jāti (639-641)

Out of these, I only see 641 in the text.

**Comment by parthopdas** [comment]
Yeah we will have to update the html. Are you able to dig out the latest version? If so, I can push it in.

**Comment by MaxxJohnson** [comment]
I see https://paliwiki.miraheze.org/wiki/Guide:Duroiselle includes the 4th
Edition, whereas the version linked in DPR's offline resources is the 3rd
Edition. Interestingly, I don't see Chapter 15 (the chapter with
dysfunctional links in the DPR offline version) in the PaliWiki link above.
Maybe Chapter 15 was removed or rearranged in the 4th Edition? I'm not
sure. Ven. Bodhirasa would know better I think.

**Comment by MaxxJohnson** [comment]
Ok, now I see this PDF of the 4th Edition that does have Chapter 15. *shrug*
