### ISSUE TITLE
Suggestion: easily jump to the next section of side-by-side commentary

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#286]
**Acceptance Criteria**
- [x] For secondary panes that are not translations (i.e. M, A and T) prev and next buttons should appear next to close button
- [ ] prev and next buttons should work expected
- [x] prev should be disabled where there is no prev & similarly for next.

=====

When reading long suttas with the commentary side-by-side, very often the sutta and commentary are segmented. When one comes to the end of the sutta section, it is possible to jump to the next section very easily, using "n" or -> from the menu, but side-by-sde commentary currently has to be closed and reopened again. It would be great to be able to just click "n" on the side-by-sde window as well and move forward to the next section.

![no next in commentary](https://user-images.githubusercontent.com/64521731/98796697-aed31a80-2431-11eb-9a32-0592b0c31450.gif)

**Comment by MaxxJohnson** [comment]
Should n/p-keyboard shortcuts work in whatever pane is selected, instead of just first pane?

**Comment by parthopdas** [comment]
They ideally should. Filed #305
