### ISSUE TITLE
Suggestion: ability to open two copies of the same text side-by-side

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#290]
**Acceptance Criteria**
- [x] Click on M while on mulā should open the same mulā on side by side pane (similarly for A and T)
- [ ] Shift+Click on M while on mulā should reopen it in the same pane (similarly for A and T)

=====

It would be great to be able to open two copies of the same text side by side with a simple shortcut like SHIFT-click on M (for Mūla). 

For example in Vinaya studies, the same text often contains a commentary on the text above, so it is useful to be able to have them side-by-side, rather than jumping back-and-forth between the two. 

Here is the rule and the commentary on the 12th saṅghādisesa side-by-sde, but both from the same sutta, opened manually though the hierarchy.

![same text side-by-side](https://user-images.githubusercontent.com/64521731/98803148-548a8780-243a-11eb-9e68-6a752272594a.png)

**Comment by MaxxJohnson** [comment]
Might as well make SHIFT + m/a/t-keys keyboard shortcuts too

**Comment by bdhrs** [comment]
good suggestion!

**Comment by parthopdas** [comment]
great suggestion. opened #304
