### ISSUE TITLE
Fully support all 17 scrips

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#293]
**Acceptance Criteria**
- [ ] Test with (a) Roman (b) Tai Tham LM (c) Hindi since these have special mutually exclusive fonts
- [ ] Navigation scenarios
- [ ] Search scenarios
- [ ] Core dictionary scenarios
- [x] Convert tab scenarios

**Dev TODO** 
- [x] Integrate https://github.com/pathnirvana/tipitaka.app/blob/master/scripts/pali-script.mjs

**Comment by MaxxJohnson** [comment]
Why don’t Tai Tham LN and Brahmi have their names written in their own script?

**Comment by parthopdas** [comment]
> Why don’t Tai Tham LN and Brahmi have their names written in their own script?

They should, I have permission from Janaka to extract the code into a new library. I will fix it there.
