### ISSUE TITLE
Feedbacks from DPR feedback form

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#301]
*A few of these may have been previously submitted as individual issues already*

3/22/2020 18:42:32 | Hey there! How great that the DPR is now online, I, and I am sure many others, benefit greatly from that. I was wondering if it might be possible for the PTS volume and pager numbering to show. I can not find any setting were I could enable that. Thank you very much for your support! Simon | simon.lenhart@gmail.com | production.5.20.0314.04 | https://www.digitalpalireader.online/DPRHTML/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

4/5/2020 5:42:19 | its great to see it back - however.....  when i try ans use Search a new page opens up in my browser Firefox , I'm using OS X, and then it just hangs there with. The Adblocker seems activated, I try and disable it but the page just bounce on and off, the Refresh button on and off. SO not working. Any help welcome as i would like to use it | venrakkhita@gmail.com | production.5.20.0402.02 | https://www.digitalpalireader.online/DPRHTML/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0

4/23/2020 2:13:08 | I wanted to find the gender for stupa (stuupa) but not even a definition came up | siluanda@gmail.com |   | production.5.20.0418.03 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

4/24/2020 19:39:48 | I was unable to see the vinaya subcommentary when I clicked on the arrow. | duetofone@gmail.com |   | production.5.20.0418.03 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
https://drive.google.com/open?id=1mZGg4kWY_6Ml4qjYtQg8f8pNyd4LNh5K, https://drive.google.com/open?id=1e7MKtJWU8QLJkETd8E8SQO5jP6luhsZ6

4/24/2020 22:12:24 | 1. Cosmetic issue: Home page (www.digitalpalireader.online) displays the date at the bottom of the page as 'NaN-....' in iPhone Safari browser (please ignore the browser version that came with this form which I am not supposed change). Please see the screenshot uploaded. NaN probably because that field is 'Not a Number' in Javascript and generally could be fixed by wrapping it in Number(field).2. Minor feature: To get help, I could press ? on the desktop browsers. How can I get help in mobile/tablet browsers where keyboard is missing? Please provide a small icon for help to press. | anatomist.noelectrons@gmail.com |   | production.5.20.0418.03 | https://www.digitalpalireader.online/_dprhtml/index.html?v=1.0 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
https://drive.google.com/open?id=1anjXD5zAZn38jjN1Tu54MOchX7kWuveI

4/26/2020 6:03:02 | I am really irritated. I used to be able to easily search 'nāma' it found it... it gave complex options, it gave a dictionary definition of it with 4 variations... now nothing..  fortunately i kept an old version , but what a hassle that is to close down my browser and open up an old version of DPR with an old browser. Now this version can't even find nāma. Giving a couple of irrelevant finds like unnama - leave a good thing alone | venrakkhita@gmail.com |   | production.5.20.0418.03 | https://www.digitalpalireader.online/_dprhtml/index.html?feature=dictionary&type=PED&query=n%C4%81ma%20&opts=xv,xd,xm,xs,xa,xk,xy,mm,ma,mt,hd | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:75.0) Gecko/20100101 Firefox/75.0

4/27/2020 4:09:04 | Requesting a feature where we can search for a sutta name cause sometimes we don't know the number and we don't know where it is. We have to google then come back so it would be nice if this can be searched directly in DPR. | This is Shraddha |   | staging.5.20.0426.03 | https://staging.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

5/11/2020 15:55:41 | Hello, you asked me to provide feedback if I found shortcomings. So jahīyati & vijahīyati The dictionary lookup identifies the correct verbbut the conjugation table does not give the secondary passive conjugation. |   |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html?loc=k.15.0.0.0.0.5.m&query=pah%C4%AByati%20jah%C4%AByati%20vijah%C4%AByati%20&para=66 | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

5/11/2020 15:55:41 | Hello, you asked me to provide feedback if I found shortcomings. So jahīyati & vijahīyati The dictionary lookup identifies the correct verbbut the conjugation table does not give the secondary passive conjugation. |   |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html?loc=k.15.0.0.0.0.5.m&query=pah%C4%AByati%20jah%C4%AByati%20vijah%C4%AByati%20&para=66 | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

5/11/2020 21:21:45 | I just submitted a screenshot but wasn't able to add a comment.See pahīyamānā  (pr.p. of pahīyati)  which is Pass. of pajahati and not  Pahoti as in the dictionary lookup. | figurehigh@gmail.com |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html?loc=d.1.0.0.8.0.16.m&query=iiyamaan&para=2 | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
https://drive.google.com/open?id=1rRXf73ip6NNWLlzS364olCq4DeOk88GS

5/12/2020 12:32:02 | Probably the two suttas appear to have the same content.In my memory these titles are;DN22  Mahasatipatthana-suttamMN10　satipatthana-suttamAlso, I think that the following contents are not included in MN10.dukkhasaccaniddesosamudayasaccaniddeso nirodhasaccaniddesomaggasaccaniddesoHonor the most noble jobs. | sanjiva888@mangara.saloon.jp |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html?loc=m.0.0.0.0.9.2.m | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

5/19/2020 21:19:18 | I think all feminine present participles take the -nt- infix.So phalaNTiyā  and not phalatiyārodaNTiyā  and not rodatiyāNote also the old Browser base DPR recognizes these as Pres. participles but the new web version does not... |   |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

5/20/2020 2:00:15 | trying for the first time to use the dictionary - in vain.Will send screen shot. | siluanda@gmail.com |   | production.5.20.0510.02 | https://www.digitalpalireader.online/_dprhtml/index.html?feature=dictionary&type=PED&query=%20%E1%B9%ADh%C4%81n%C4%81ni&opts=xv,xd,xm,xs,xa,xk,xy,mm,ma,mt,ft,hd | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
https://drive.google.com/open?id=1HuLmAwN7UXwlGTAho1VzLlEU3JB3Zf8O

6/9/2020 3:44:10 | Page appears to be broken, unable to load files. I have sent a screenshot. | arfh@xplornet.com |   | production.5.20.0604.01 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:76.0) Gecko/20100101 Firefox/76.0
https://drive.google.com/open?id=1lPkBbdCih6EnUCx8KkHJQmhA82xgNK4A

6/13/2020 17:50:59 | Hi, I can't see the two translation icons explained in the "Using the Digital Pali Reader" video at minute 4.13, I only see one type of translation icon.Greetins | riccardo.luise.info@gmail.com |   | production.5.20.0610.02 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

6/28/2020 15:38:01 | I could not find option to search a sutta by its name. Eg. Abhayasutta.m/ Kutaagaarsutta.m. | sampada82@gmail.com |   | production.5.20.0610.02 | https://www.digitalpalireader.online/_dprhtml/index.html?feature=search&type=0&query=kut%C4%81g%C4%81rasutta%E1%B9%83&MAT=m&set=dmsak&book=1&part=1&rx=false | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

6/28/2020 20:56:45 | Layout is confusing and messy. Also, see for errors uploaded zip-file.What we used it a couple of months ago, with just the text and clickable words was easier. (Clicking on the words rendered a field with pali definition, if memory serves.) | meshing.000@gmail.com |   | production.5.20.0610.02 | https://www.digitalpalireader.online/_dprhtml/index.html?loc=m.0.0.0.0.7.x.m | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
https://drive.google.com/open?id=14vHR-TO_mzhPTVaOkE0QxZBHSh671dCu

7/28/2020 13:11:05 | Wondering if there is still a way to have this download for off-line use? Can't see any option on the screens (am I missing it?) | royce.wiles@gmail.com |   | production.5.20.0713.01 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

7/29/2020 15:49:40 | Congratulations on the new DPR. It worked seamlessly in the latest version of Firefox in Ubuntu 16.04 in that I could read the Visuddhimagga with the pali and translation side by side. However, when I downloaded the DPR contents, the last tile with a pagoda shape on it and labelled 'translation' was missing and now I have no access to the translation(s) either online or offline.It is not clear from your website how to access the DPR offline. I bookmarked your website and used that bookmark. I wonder if that is the problem and I should be doing something else. | stefankarpik@hotmail.com |   | production.5.20.0728.02 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

8/4/2020 4:24:40 | Retroflexive/Cerebral underdotted letters render correctly in Chrome and Edge yet incorrectly as being in a slightly smaller case in Firefox. With Firefox, the text is somewhat more difficult to read as such. | kvam.jay@gmail.com |   | production.5.20.0730.01 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
https://drive.google.com/open?id=1A8uBidVpfSyvz7LiUkzgPPs9sOU6hH-s

10/2/2020 21:36:56 | please provide the website in devnagri along with options of marathi and hindi languages translation. | rajenhiwale211@gmail.com |   | production.5.20.0919.01 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

11/26/2020 18:20:53 | How to operate DPR in Devanagari script |   |   | production.5.20.0919.01 | https://www.digitalpalireader.online/_dprhtml/index.html | Mozilla/5.0 (Linux; Android 10; Redmi K20 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Mobile Safari/537.36

**Comment by parthopdas** [comment]
please break this down into logically grouped issues with crisp ACs
