### ISSUE TITLE
DPR broken - appInsights

### ISSUE THREAD

**Issue by dangeol** [digitalpalireader/digitalpalireader#309]
AC:
- [ ] Ensure failsafe
- [ ] Ensure telemetry is not reported on localhost

About an hour ago DPR in production stopped working due to a problem related to ApplicationInsightsAnalytics.
Interestingly, also local dev environment is impacted.
This is a temporary outage, and has been reported by three users from different continents.

![image](https://user-images.githubusercontent.com/44405794/103682139-be319880-4f88-11eb-8f79-f98dc3df793a.png)

**Comment by parthopdas** [comment]
this hasn't happened since, kindly reopen if it repros.
