### ISSUE TITLE
search in Aṭṭakathā terms a word (upapāramī) I can see the results, but when I click to open that place in Atthakata, it is not opening it.

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#320]
Here is the repro: https://www.digitalpalireader.online/_dprhtml/index.html?loc=k.10.1.1.0.0.0.a&query=upap%C4%81ram%C4%AB&para=597

**Comment by MaxxJohnson** [comment]
I can't reproduce. It is opening to the text for me.

**Comment by MaxxJohnson** [comment]
Ok, I misunderstood the issue. Now I can reproduce and cannot open to the text for this word. I wonder if there are other words where this happens.

**Comment by rrogowski** [comment]
Confirmed working by Venerable Bodhirasa.
