### ISSUE TITLE
Only the PED definition should scroll not the CPED definitions

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#325]
Eg  in https://www.digitalpalireader.online/_dprhtml/index.html?loc=d.0.0.0.0.0.0.m&analysis=anekapariyaayena

If you scroll up the bottom pane, the CPED definitions (in red) scroll up as well. They should stay in place while only the PED definition (the lengthy description) should scroll

**Comment by MaxxJohnson** [comment]
Excellent. Same issue as #323.

To clarify, the CPED definitions are blue, and the DPR analysis word breakup is red. Both red and blue and everything in that top strip should remain locked on top while the lengthier PED definition can scroll.

**Comment by parthopdas** [comment]
Correct. Please feel to mark this issue as dup.
