### ISSUE TITLE
Create clickable button that displays shortcuts. Add icon to settings dropdown.

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#328]
From Feedback form: "Minor feature: To get help, I could press ? on the desktop browsers. How can I get help in mobile/tablet browsers where keyboard is missing? Please provide a small icon for help to press."

AC:
- [ ] Create a clickable button that displays shortcuts.

Suggestion: The current HELP icon ("?" icon) that leads to the "how to" youtube video could be made to cause a dropdown (in the style of the settings and dark reader dropdown menus) that allows you to choose either the video (e.g. tv icon) or the shortcut list (e.g. keyboard icon)

![image](https://user-images.githubusercontent.com/60581658/125197879-7b00fc80-e22d-11eb-8509-32c998e0dd6d.png)

And while we are here, it seems we should add an identifying icon to identify the dropdown that has the "Install components" and "settings" features.

AC:

- [ ] Add identifying icon to "Install components & Settings" dropdown

**Comment by parthopdas** [comment]
Please reactivate if necessary with a prior art i.e. a product that does something similar.
