### ISSUE TITLE
Tools > Dictionary search > DPR Analysis bug

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#332]
DPR Analysis search does not display PED definition when search is conducted straight away from home page.

PED definition does begin to display however after clicking on a word in a text.

AC:
- [ ] DPR Analysis search in tools tab displays PED definition when search is conducted straight away from home page

![image](https://user-images.githubusercontent.com/60581658/111909196-b2eff400-8a32-11eb-917d-4a431c9c0a3b.png)

**Comment by rrogowski** [comment]
As an FYI for tracking purposes, I introduced this regression in #330. Pushing up a fix soon!

**Comment by parthopdas** [comment]
@MaxxJohnson thanks for adding the screenshot.

**Comment by rrogowski** [comment]
V @bdhrs has confirmed this is now working on staging!
