### ISSUE TITLE
ability to use dictionary in search results for "aṭṭḥakathā terms" and "ṭīkā terms"

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#335]
similar to #260 

related to searching in
tools > aṭṭhakathā terms
tools > ṭīkā terms

when searching in aṭṭhakathā and ṭīkā it is useful to be able to click on words in the search results and see dictionary definitions. currently the sutta has to be opened in a new tab to see the dictionaries. 

AC:
- [ ] clicking on words in search results opens DPR analysis in the bottom pane

![aṭṭhakathā ṭīkā search](https://user-images.githubusercontent.com/64521731/111930054-05d2b580-8ade-11eb-9b90-faae99233564.png)

**Comment by bdhrs** [comment]
great update! so useful for hunting down word definitions. 

it introduced one glitch though. the ped history is now up at the top. 

![2021-06-13_20-46](https://user-images.githubusercontent.com/64521731/121813192-9279b380-cc88-11eb-9113-8e56e9b1f765.png)

**Comment by dangeol** [comment]
@bdhrs thanks for your feedback. I just compared production and staging and could not find a difference. DPR Analysis history is at the bottom and PED history at the top. Am I missing something?

**Comment by bdhrs** [comment]
normally the pts history is buried inside the pts dictionary like this, visible by rolling the mouse over it. 

![normal](https://user-images.githubusercontent.com/64521731/121833223-8114c380-cce9-11eb-9a5f-99f9d3ee44da.png)

in the aṭṭhakathā and ṭīkā search pages, it is now up at the top, in an area unrelated to pts dictionary. 

![new](https://user-images.githubusercontent.com/64521731/121833297-aacdea80-cce9-11eb-969f-1b851b13217e.png)

**Comment by dangeol** [comment]
Thanks @bdhrs, now I see. This will be fixed this week.

**Comment by dangeol** [comment]
This should now be fixed.

**Comment by parthopdas** [comment]
@dangeol in general please do not close the issues yourself. 

they should be verified & closed by the person who opened the issue. v @bdhrs in this case.

**Comment by dangeol** [comment]
Sure, I agree.
