### ISSUE TITLE
use NPM to manage third-party dependencies

### ISSUE THREAD

**Issue by rrogowski** [digitalpalireader/digitalpalireader#339]
We are currently storing third-party JavaScript modules in [_dprhtml/js/external](https://github.com/digitalpalireader/digitalpalireader/tree/master/_dprhtml/js/external). Without having some kind of webpack (browserify, etc.) configuration in place, it is non-trivial to use imports / requires / NPM modules in the browser, but that will change as we modernize our tech stack.

The following modules should be added to our `package.json` and used in place of the files living in `_dprhtml/js/external` (though not necessarily all at once):
- [ ] bootstrap@4.4.1
- [ ] fontawesome@4.7.0
- [ ] jquery@3.4.1
- [ ] knockout@3.5.0
- [ ] nanobar@0.4.2
- [ ] popper.js@1.16.0

**Note**: We are also using jquery-resizable@0.35, but I don't think this is the same library available on NPM (https://www.npmjs.com/package/jquery-resizable). For the version we are currently using, see https://github.com/RickStrahl/jquery-resizable/releases/tag/0.35.

**Comment by parthopdas** [comment]
this is required so we have all dependencies available at one shot for reliable PWA offlining

this will be fixed as part of the the ES6/webpack integration. #96 

please reactivate if you disagree
