### ISSUE TITLE
"Change script" setting displayed on landing page

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#341]
As mentioned by ven @bdhrs, having the change script setting buried in the settings menu decreases access for some people.

Maybe all scripts should be displayed outright on the landing page (not hidden in a dropdown) so that someone who recognizes one of them might see it and click on it so that navigating other parts of the page could make sense to them.

- [ ] change script setting available on landing page

**Comment by parthopdas** [comment]
Current architecture of the product make this very very difficult to accomplish with breaking a bunch of things.

This will be fixed when we move to react.
