### ISSUE TITLE
Multiple translation link icons displayed

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#349]
For DN 16.4, there are several icon links to Ven Anandajoti's translations for some reason. It seems to be linking to different parts of the same sutta. Maybe there is a good reason that I am not aware of for there to be so many links to different sections.
![image](https://user-images.githubusercontent.com/60581658/118407254-f4c1a300-b64d-11eb-9ba6-6ffd025c06c8.png)
I don't know if this behavior is found elsewhere with different texts.

- [ ] Make it so only 1 icon link is displayed if that is what is appropriate, or make no changes if the multiple links are appropriate

**Comment by parthopdas** [comment]
All of these links were present in the original. best to check with v yuttadhammo.
