### ISSUE TITLE
include forms of words

### ISSUE THREAD

**Issue by bksubhuti** [digitalpalireader/digitalpalireader#66]
DPRWeb needs forms of the words added to the definitions.
both verbs nouns and also adjectives.

Very helpful for beginners especially the irregular or advaced forms..
kar 
or 
bhagavant

This should already be accesssible in code or be fairly simple to implement for the dictionary parser to do.  (It should already have this information).  It is rarely seen in the old DPR if at all.

Old dpr used to have a declension display tab.
However, I'm asking for the actual declension to be displayed rather than a chart.

Please see the latest TPP vid I sent.. where I show grammar.. also the original TPP 17 min one I sent a while back.  One of the dictionaries has this already.  but this dictionary is not as "on mark" as the new dpr.

code will be available under bksubhuti soon

Perhaps it can be formulated as it is parsing codes are given.  (There are many times multiple choices.. eg.  data and gen are similar).
Then display that code as a fully transliterated form ..

**Comment by parthopdas** [comment]
not a priority for now. please reactivate if you feel strongly about this.
