### ISSUE TITLE
For slow networks indicate percentage completion and hint that things havent stalled.

### ISSUE THREAD

**Issue by bksubhuti** [digitalpalireader/digitalpalireader#67]
One of the issues (main issues) with dprweb is the slowness to load.  It may be perceived as broken when in fact, it is  a slow connection for those in Asia (a decent day is 50-60 KB/s
(thats a big B for Bytes).  100 KB/s and 200 speeds means things are working really well, usually in off hours.

Solution:  Have the dots rotaing in a circle thing.
If possible show a feedback on loading progress because.. even though we get the "hourglass" if there is nothing happening for a while.. we still  feedback.. percentage is good.
Perhaps load the light stuff first.  Then load the heavy stuff.
There is an async
https://www.w3schools.com/tags/att_script_async.asp

**Comment by bksubhuti** [comment]
Several examples would be Google drive uploads or youtube uploads or archive.org uploads.  all have some type of feedback

**Comment by parthopdas** [comment]
The request here I think is to show (a) percentage completion (b) some activity on the screen through some marquee to indicate that things aren't stalled.

**Comment by DPRAdmin** [comment]
Closing it as its done.
