### ISSUE TITLE
Navigation sidebar: Implement context menu in sidebar (complete with place holders)

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#8]
Implement these functionality in the navigation sidebar
![image](https://user-images.githubusercontent.com/2140460/72665531-d85f2780-3a54-11ea-9cae-527dacc5071c.png)

**Comment by smkvr98** [comment]
#27 and #26 address this . Buttons associated with functions that are in the process of being ported have been disabled .

**Comment by smkvr98** [comment]
# Present Issues/Pending
## 1.Thai-Myanmar Tipitaka Alternation Button .
Solution : 
	Change regex in digitalpalireader.makeWebAppropriate() to include openplace with alt parameter .
	Fix chromeFileExists() for web. Presently returns true for non-existent files too . 
## 2.Implement Convert/Send/....
Port respective functions

**Comment by smkvr98** [comment]
- [ ] Implement export functionality .
- [ ] Implement save functionality .
- [ ] Implement convert functionality .

**Comment by DPRAdmin** [comment]
Closing it as it is done.
